name: Docker Image Publish
run-name: ${{ github.actor }} is updating the docker image 🚀
on: 
  push:
    branch:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image-publish.yml'
  pull_request:
    branch:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image-publish.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update_docker_image:
    name: Build and Push Docker image to the docker hub
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            hielamonboren/vulkan-learning
          tags: |
            type=raw,value=dev-latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}