name: Docker Image Publish
run-name: ${{ github.actor }} is updating the docker image 🚀
on: 
  push:
    branch:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image-publish.yml'
  pull_request:
    branch:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image-publish.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository workspace Test
        run: ls ${{ github.workspace }}/
      - run: echo "🍏 This job's status is ${{ job.status }}."